// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM8oedhtX1zYYYzqDHviEVVeUV1pjBz0A',
    appId: '1:648277821301:web:8eff936ce4ee816404f53c',
    messagingSenderId: '648277821301',
    projectId: 'pizda-slonihi',
    authDomain: 'pizda-slonihi.firebaseapp.com',
    storageBucket: 'pizda-slonihi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Qj1FNuPV6X9cPesvxf5K9pY7EcjJgKE',
    appId: '1:648277821301:android:c420053d53313d6404f53c',
    messagingSenderId: '648277821301',
    projectId: 'pizda-slonihi',
    storageBucket: 'pizda-slonihi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM8oedhtX1zYYYzqDHviEVVeUV1pjBz0A',
    appId: '1:648277821301:web:2961b7f87834feff04f53c',
    messagingSenderId: '648277821301',
    projectId: 'pizda-slonihi',
    authDomain: 'pizda-slonihi.firebaseapp.com',
    storageBucket: 'pizda-slonihi.firebasestorage.app',
  );

}